name: The Train App CI/CD Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Creating Docker Image for the Django Project
    
    steps:
    - uses: actions/checkout@v3
      name: Checkout the repo
      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag the-train-app:latest
      
    - name: Log into the Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: devangmehta/the-train-app
    
    - name: Build and push the Docker image to docker registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
      
